# Generated by Django 5.0.4 on 2024-05-23 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(db_column='idEstado', primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(db_column='idPedido', primary_key=True, serialize=False)),
                ('foto_producto', models.ImageField(blank=True, null=True, upload_to='')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('id_estado', models.ForeignKey(db_column='idEstado', on_delete=django.db.models.deletion.CASCADE, to='administracion.estado')),
            ],
        ),
    ]
