# Generated by Django 5.0.4 on 2024-05-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_remove_pedido_foto_producto_remove_pedido_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
