# Generated by Django 5.0.4 on 2024-05-24 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_pedido_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id_estado',
            field=models.ForeignKey(db_column='idEstado', default=3, on_delete=django.db.models.deletion.CASCADE, to='administracion.estado'),
        ),
    ]
