# Generated by Django 5.0.4 on 2024-05-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_alter_pedido_id_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
