# Generated by Django 5.0.4 on 2024-05-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_alter_pedido_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='precio',
            new_name='precio_total',
        ),
    ]
